### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by rashil2000** [Milo123459/salt#10]
I like using cargo as package manager 😊

**Comment by Milo123459** [comment]
I'll publish it in a few hours. It'll be named salt-cli. I have a question, how can I make sure that if you do `cargo install salt-cli` you can still do `salt` and you don't have to do `salt-cli`. Ideas?

**Comment by rashil2000** [comment]
I saw that the name `salt` was already taken 😅

Does this do what you require https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries ?

**Comment by Milo123459** [comment]
I think that should work. I'll check it out.

**Comment by Milo123459** [comment]
Okay, for clear-of-mind I'm contacting the owner of the salt crate to see if I can have ownership.

Also, may I ask how you found salt?

**Comment by rashil2000** [comment]
> Okay, for clear-of-mind I'm contacting the owner of the salt crate to see if I can have ownership.

Yeah that's a good idea considering the current `salt` crate has been abandoned.

> Also, may I ask how you found salt?

Interesting question!
I was updating Scoop and found an app called Glitter - I'm a sucker for Rust CLI tools and checked out your repos if you had more interesting tools. Salt was one of them!

**Comment by Milo123459** [comment]
1) Yup, for now just use Scoop.

2) Wow, elaborate!

**Comment by Milo123459** [comment]
Good news! I should be getting the crate sometime today! I'll keep you posted :)

**Comment by Milo123459** [comment]
Published!

**Comment by rashil2000** [comment]
Great news!

**Comment by Milo123459** [comment]
Hey, sorry for commenting and giving you a notification! I'm just curious, is salt still a tool you use a lot?

If so, please give me some feedback in a discussion. I really do appreciate it.

Thank you, @rashil2000

**Comment by rashil2000** [comment]
I've been busy with tests the past few weeks, so I haven't used it much since then. Will definitely leave some feedback when I get the opportunity to explore it fully. 

(One thing that does come to mind: I don't like apps/tools cluttering my Home directory, would it be possible to for salt to store its information in some other folder, perhaps `~/.cache/salt` or `~/.config/salt` instead of `~/.salt`?

**Comment by Milo123459** [comment]
Thanks for the suggestion! (Hope the tests go well)

Sure. I'll add configurable paths, but migration will be manual (ie, copying over salt.json to the new destination)

**Comment by rashil2000** [comment]
Hey, thanks for the wishes!

> ...migration will be manual...

No problemo!
